import { StyleSheet } from "react-native";
import { getStatusBarHeight } from "react-native-iphone-x-helper";
import { COLORS, FONTS } from "../../theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingBottom: 20,
    paddingTop: 16,
    marginTop: getStatusBarHeight(),
  },
  categoryText: {
    fontSize: 18,
    color: COLORS.heading,
    fontFamily: FONTS.title700,
    marginTop: 32,
    marginBottom: 12,
    paddingHorizontal: 24,
  },
  title: {
    color: COLORS.heading,
    fontSize: 20,
    fontFamily: FONTS.title700,
  },
  selectServerWrapper: {
    marginTop: 32,
    marginBottom: 28,
    paddingHorizontal: 24,
  },
  selectServer: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.secondary40,
    borderRadius: 8,
    height: 68,
  },
  selectServerBox: {
    width: 64,
    height: 68,
    borderRadius: 8,
    borderRightWidth: 1,
    borderRightColor: COLORS.secondary40,
  },
  selectServerContent: {
    alignItems: "center",
    flexDirection: "row",
  },
  selectServerText: {
    marginRight: 24,
    fontSize: 18,
    fontFamily: FONTS.title700,
    color: COLORS.heading,
    marginLeft: 35,
  },
  dateTimeWrapper: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 24,
    marginBottom: 28,
  },
  dateWrapper: {},
  dateText: {
    fontSize: 18,
    color: COLORS.heading,
    fontFamily: FONTS.title700,
    marginBottom: 16,
  },
  dateInput: {
    borderColor: COLORS.secondary40,
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: COLORS.secondary50,
    color: COLORS.heading,
    height: 48,
    width: 156,
    padding: 16,
  },
  timeWrapper: {},
  timeText: {
    fontSize: 18,
    color: COLORS.heading,
    fontFamily: FONTS.title700,
    marginBottom: 16,
  },
  timeInput: {
    borderColor: COLORS.secondary40,
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: COLORS.secondary50,
    color: COLORS.heading,
    height: 48,
    width: 156,
    padding: 16,
  },
  descriptionHeaderWrapper: {
    alignItems: "center",
    flexDirection: "row",
    paddingHorizontal: 24,
    justifyContent: "space-between",
    marginBottom: 12,
  },
  descriptionText: {
    fontSize: 18,
    fontFamily: FONTS.title700,
    color: COLORS.heading,
  },
  descriptionMaxCharacters: {
    fontSize: 13,
    fontFamily: FONTS.text400,
    color: COLORS.highlight,
  },
  descriptionInputWrapper: {
    paddingHorizontal: 24,
  },
  descriptionInput: {
    borderColor: COLORS.secondary40,
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: COLORS.secondary50,
    color: COLORS.heading,
    height: 100,
    width: "100%",
    padding: 8,
  },
  scheduleButtonWrapper: {
    paddingHorizontal: 24,
    marginTop: "auto",
    marginBottom: 10,
  },
  scheduleButton: {
    width: "100%",
    height: 56,
    backgroundColor: COLORS.primary,
    textAlign: "center",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 8,
  },
  scheduleButtonText: {
    color: COLORS.heading,
    fontSize: 15,
    fontFamily: FONTS.text500,
    lineHeight: 25,
  },
});
